version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: "${MANAGEMENT_API_SECRET}"
        port: 4466
        databases:
          default:
            connector: postgres
            host: ${POSTGRES_HOST}
            port: ${POSTGRES_PORT}
            user: "${POSTGRES_USER}"
            password: "${POSTGRES_PASSWORD}"
            migrations: true
